### ISSUE TITLE
Sample working ?

### ISSUE THREAD

**Issue by PhilippeCorreges** [pierrem/WordPress-API-Demo#1]
Bonjour,
Je suis ravi d'être tombé par hasard sur ce repo :-)
Par contre, je compile sur Xcode et je lance l'appli et les posts ne sont pas affichés. J'imagine que l'url concernée est  https://public-api.wordpress.com/rest/v1.1/sites/developer.wordpress.com.

J'ai donc installé sur mon site wordpress le plugin WP REST API de GSoc2013 pour exposer la bonne URL GET.
L'appli reste muette. La page de posts d'affiche pas elle reste vide. Si je passe par le navigateur, via l'url de l'api get, il revient à la page d'accueil du site.

PS: Je ne connais pas bien swift et je souhaite m'y mettre (aussi) pour proposer à mes clients du développement iphone. Votre exemple est un super bon début je pense.

Merci

**Comment by pierrem** [comment]
Bonjour,

Je n’ai pas le temps de regarder ça en détail maintenant, mais il s’agit apparement d’un problème d’interface utilisateur.
Le soft a l’air de fonctionner sur iPad (ou simulateur), par contre il y a un soucis avec les iPhones.
Une incompatibilité avec iOS 9.X ? Un pb avec le Storyboard ?

Je regarderai ça plus tard…

Cordialement,

—
Pierre Marty

**Comment by PhilippeCorreges** [comment]
ok merci.

**Comment by pierrem** [comment]
Fixed

**Comment by PhilippeCorreges** [comment]
I gonna test it and keep u posted.

Thanks

**Comment by PhilippeCorreges** [comment]
Bonjour,
Je viens de vérifier.
Ainsi, la page s'affiche maintenant avec le Titre POST. Les posts semblent être séparés par des lignes mais le texte n'apparaît pas.
Une idée ?

**Comment by PhilippeCorreges** [comment]
Je précise que je suis en http only. A mon avis c'est le problème.

**Comment by pierrem** [comment]
Et sur l’adresse d’origine de l’exemple, ça fonctionne ?
https://public-api.wordpress.com/rest/v1.1/sites/developer.wordpress.com https://public-api.wordpress.com/rest/v1.1/sites/developer.wordpress.com

Ensuite je ne sais plus exactement quelle manip j’avais fait pour connecter mon site (hébergé chez 1&1) au serveur wordpress pour bénéficier le l’API WP sur mon site.
Je crois qu’il faut juste le déclarer coté sur wordpress.com http://wordpress.com/.

https://public-api.wordpress.com/rest/v1.1/sites/www.alpeslog.com https://public-api.wordpress.com/rest/v1.1/sites/www.alpeslog.com

Une autre solution est sans doute d’utiliser le plugin REST API : http://v2.wp-api.org http://v2.wp-api.org/, mais je n’ai pas encore essayé et l’API est peut être différente…

Cordialement,

—
Pierre Marty
www.alpeslog.com

**Comment by PhilippeCorreges** [comment]
Bonjour.
Désolé pour ma réponse tardive.

En réponse à vos commentaires : 
- En utilisant https://public-api.wordpress.com/rest/v1.1/sites/developer.wordpress.com cela fonctionne à merveille.
- J'utilise le plugin http://v2.wp-api.org/ . 

Quel est le plugin que vous utilisez ? Si j'utilise le même cela devrait fonctionner.

Merci pour vos réponses.
